version: '3.8'
services:

  db:
    container_name: db
    image: postgres:15.0-alpine
    volumes: 
      - dbdata:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_bewise

  db_test:
    container_name: 'db_test'
    image: postgres:15.0-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test

  fastapi_app:
    container_name: fastapi_app
    build:
      context: ../
    restart: on-failure
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  dbdata: